### ISSUE TITLE
backspace doesn't remove element on Mac OS X

### ISSUE THREAD

**Issue by avilleret** [ossia/score#100]

**Comment by reno-** [comment]
To remove an élément from the scenario, you must use delete, and not backspace.
From what I remember, Backspace is used to remove an element from the device explorer.

**Comment by theod** [comment]
sorry for the noise but where is the delete button on a Mac book pro keyboard ?

**Comment by nvuaille** [comment]
I guess that's "function + backspace"

**Comment by theod** [comment]
I've just tried "function + backspace", "cmd + backspace", "alt + backspace", "ctrl + backspace" and "shift + backspace" but none of them works.

but in any case I would expect a more easy access like "backspace" to delete something.
Am I the only one ? @bltzr, @avilleret and @jln- ?

**Comment by avilleret** [comment]
I agree with @theod, backspace is a good canditate to delete things.
IIRC, when I right click on the score element, there is a "Delete" item in the menu with a backspace icon beside it, that why I was expecting backspace to do the same as the menu item, which is not, hence this issue

@reno- with a PC keyboard plugged on a Mac, del (or suppr, depending on how you name it) doesn't do anything, neither on the device explorer nor on the score itself

but command + del do remove the event on the score ! despite of the announced shortcut
since Apple finds this key useless, there no on their keyboard, and lots of people can't access this shortcut easily

**Comment by nvuaille** [comment]
Yep, there's a problem : OSX keep for itself lot of shortcuts and doesn't like "del" key, so we have to review lot of them
By the way, we first set "backspace" to clear the contents (delete process from selected constraints and states from event) and "del" to delete (i.e. remove temporal element), because we're coding on linux, with all that keys on keyboard =) 

So we can invert it but there's still a work to do upon shortcuts.
