### ISSUE TITLE
start and end state values are erased by min an max when creating an automation

### ISSUE THREAD

**Issue by theod** [ossia/score#106]
if I create a constraint and then I add an address value to the start and the end then, when I create a automation on the same address value, the state values are erased by the min and the max of the address.

**Comment by jcelerier** [comment]
this one is actually tricky : 

for this scenario : 
![state](https://cloud.githubusercontent.com/assets/2772730/11927763/2e7408d8-a7cf-11e5-88df-b7f0252e6150.png)

now, what happens if I switch the address of the curve from /a to /b ? 
Should the shape of the curve stay the same, and the states change ? or should the states stay the same and the first / last point of the curve change ?

**Comment by theod** [comment]
I would expect the second behavior but I add @reno-, @bltzr, @avilleret and @jln- to have their point of view.

**Comment by reno-** [comment]
Yes I agree with @theod. When I set values in states,  I expect that they cannot be changed until I do it explicitly

**Comment by jcelerier** [comment]
I'm closing : I think that the "Add process > automation" should be a last resort to create automations (it's a bit of a "debug" feature) : most of the time you want create curve, interpolate states, sequence mechanism etc... which does not have this problem
