### ISSUE TITLE
pattern constraint is not resized when resizing a loop

### ISSUE THREAD

**Issue by theod** [ossia/score#107]
I've tested all the resize mode (scale, grow/shrink and keep duration).

**Comment by jcelerier** [comment]
This is actually a feature : I thought that it would be weird since by default the loop pattern is created of the same size as the parent constraint hence resizing it would prevent from ever having more than one loop iteration, which is I think not coherent with the behaviour of other software sequencers (e.g. Live).

What would be the best default in your opinion ?

**Comment by theod** [comment]
I add @reno-, @bltzr, @avilleret and @jln- to get their opinion.

if we consider the pattern as the content of the loop, I would propose to have the same behavior than for other contents. so in scale mode I would expect to scale the pattern, in keep duration mode to keep pattern duration, ...

**Comment by reno-** [comment]
It's a bit hard to have a strong opinion on this now. Because both possibilities have their pros and their cons.
I will try using loops to get my opinion on this.

**Comment by bltzr** [comment]
I'm not sure, but maybe you're right, @theod , that this should follow the scale mode - maybe with it being set to scale by default when handling ?
but then, if we did so, what would happen to other processes ?
I've put the link of this issue in the Lyon topic list

**Comment by jcelerier** [comment]
not relevant anymore
