### ISSUE TITLE
Midi input device cannot be edited

### ISSUE THREAD

**Issue by jln-** [ossia/score#1107]
Using score v3.0.0-a18, created Midi input device cannot be edited. Steps to reproduce:

- From the D-E: Add device 
- Select Midi input (leave 'create whole tree' unticked)
- Right-click on the Midi device name, and select 'edit'
- In the setup window, toggle on 'create whole tree', click OK
- In the D-E, device has no children etc.

Device has to be removed, then created again with the 'Create whole tree' option so it is properly created.

**Comment by jcelerier** [comment]
hmmm so, I'm not really sure on how to handle this properly: the device is indeed edited, but you have to refresh it manually afterwards to update it and see the new nodes.
This is because if it was e.g. an oscquery device (score doesn't really make a difference on what "kind" of device it is by principle) you don't want to reload the entire device if you change a settings on it, for instance the port, because you may loose data.

**Comment by jcelerier** [comment]
tried to fix it with a special flag for the midi device, seems to work, hopefully it does not break anything unforeseen !
