### ISSUE TITLE
Segfault when opening a score on debian

### ISSUE THREAD

**Issue by ju1ius** [ossia/score#1130]
Hi,

This is the first time I try to use ossia score.
I just downloaded the latest linux appimage (3.0.0-a21), and the program segfaults whenever trying open or create a new project (e.g. clicking on New on the welcome screen or opening an example from the user library).

I'm running debian sid.

```
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Case insensitive sorting unsupported in the posix collation implementation (:0)
Warning: Numeric mode unsupported in the posix collation implementation (:0)
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1038, resource id: 14874826, major code: 40 (TranslateCoords), minor code: 0 (:0)
#0 0x00000000072406af llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/tmp/.mount_ossia-r5y7JL/usr/bin/ossia-score+0x72406af)
#1 0x000000000723e782 llvm::sys::RunSignalHandlers() (/tmp/.mount_ossia-r5y7JL/usr/bin/ossia-score+0x723e782)
#2 0x00000000072409e5 (/tmp/.mount_ossia-r5y7JL/usr/bin/ossia-score+0x72409e5)
#3 0x00007fe635315140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14140)
Erreur de segmentation
```

**Comment by ju1ius** [comment]
FYI, the highest release that doesn't crash instantly when opening files is [version 3.0.0-a14-1](https://github.com/ossia/score/releases/download/v3.0.0-a14-1/ossia.score-3.0.0-a14-1-linux-amd64.AppImage), so looks like a bug might have been introduced in 3.0.0-a15... Maybe related to the zeroconf feature ?

**Comment by jcelerier** [comment]
Hello, thanks for testing (and apologies for the crash).

On which linux distro are you ? The release is tested with archlinux and latest ubuntus

**Comment by ju1ius** [comment]
> apologies for the crash

Hey no worries, this is an alpha release after all. :wink: 

My distro is Debian sid, so should be pretty close to latest ubuntu I guess...

**Comment by jcelerier** [comment]
okay, I had tested on debian testing, will try sid the next few days

**Comment by lucasbardis** [comment]
Hello, similar error here on linux debian buster GNOME 3.30.2 with backport with the release ossia.score-3.0.0-a21-linux-amd64
Ossia is launching but close when selecting "new". 
I have launched with root and have this error : 
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QFontDatabase: Cannot find font directory /opt/score-sdk/qt5-static/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
("/home/useur01/Documents/score/addons")
(QToolBarLayout(0xcdeef10), QToolBarExtension(0xcdfd610, name = "qt_toolbar_ext_button"), QAction(0xcdfd920), QWidgetAction(0xcdfdf10), QLabel(0xcdfdcc0, name = "TimeLabel"), QToolButton(0xcdfe000), QToolButton(0xcdfe500), QToolButton(0xcdf2bf0), QToolButton(0xcdf3360), QWidgetAction(0xcebbe00), QWidget(0xcdfe040, name = "SpeedSlider"))
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Case insensitive sorting unsupported in the posix collation implementation (:0)
Warning: Numeric mode unsupported in the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Case insensitive sorting unsupported in the posix collation implementation (:0)
Warning: Numeric mode unsupported in the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Case insensitive sorting unsupported in the posix collation implementation (:0)
Warning: Numeric mode unsupported in the posix collation implementation (:0)
ossia-score(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x72406af]
ossia-score(_ZN4llvm3sys17RunSignalHandlersEv+0x22)[0x723e782]
ossia-score[0x72409e5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fa6d4290730]
[1]    3186 segmentation fault  /home/useur01/AppImages/ossia*
`

and with user : 
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

[1]    3228 abort      ./AppImages/ossia.score-3.0.0-a21-linux-amd64.AppImage
`

**Comment by jcelerier** [comment]
hmmm, so it seems that it does not work on wayland - do you know if you could try running it under XWayland ?

**Comment by ju1ius** [comment]
@jcelerier FYI, I'm running debian sid under XFCE, so under a X server _not_ Wayland.
Thus the issue of crashing when opening file is not related to wayland. Changing the title back to reflect this fact.

**Comment by jcelerier** [comment]
ah, thanks, two different issues then

**Comment by jcelerier** [comment]
@ju1ius could you try the a22 ? I installed a clean debian, reproduced & fixed - now it should work

**Comment by ju1ius** [comment]
Hi @jcelerier,

I only did a really quick test but opening/saving seems to work so far...
Thanks !

**Comment by jcelerier** [comment]
thanks to you for reporting the issue :-)
