### ISSUE TITLE
crash on play or on mouse selection

### ISSUE THREAD

**Issue by avilleret** [ossia/score#121]
with 1.0.0-a36, here is a backtrace : https://gist.github.com/avilleret/6275da96c701e752e184

**Comment by avilleret** [comment]
here is another one triggered by selecting a node with mouse click&drag : https://gist.github.com/avilleret/c143d836ce2f91151d97

**Comment by jcelerier** [comment]
Both crashes seems to be related to the parsing of an expression in a condition; could you share the condition that you had ? maybe it's some invalid character that causes the crash or something like this

**Comment by avilleret** [comment]
nothing, maybe that's why it's crashing...
I've just retry it, and here is how to reproduce : 
1. open i-score
2. create a node with CTLR + clic
3. try to select the node by click & drag, when I reach the middle of the node circle it crashes

this is on Ubuntu 15.10

**Comment by jcelerier** [comment]
ahhh, did you follow the small part in the Quick install section of the README ? 

I think that this is due to incompatibility between packages built on ubuntu 14.04 and 15.10; for now i-score should be rebuilt from source on your computer. Or maybe with something like https://build.opensuse.org/ but I never had the time to set it up.
Other possibility is to do a completely static build of i-score which does not even link to the system's libc / libc++ (this is where the problem comes from I think), but this will prevent from using external plug-ins later.

**Comment by avilleret** [comment]
following `Quick Install` step in README doesn't help, 
so I'll build it from scratch. thanks

**Comment by avilleret** [comment]
you're right, building from scratch solve the issue, thanks
