### ISSUE TITLE
Color automation OSC control not working with basic OSC Device

### ISSUE THREAD

**Issue by sofian** [ossia/score#1352]
Adding an OSC Device named "OSCDevice" with child "background" (type: Vec3f or Vec4f) does not work. Set output of color automation to "OSCDevice:/background@[color.argb]", when playing the values stay at [0, 0, 0]. Strangely, if I add an OSC device of type "dlight" and add a "background" child of same type (Vec3f) it does work (of course after renaming output of color automation to "dlight:/background@[color.argb]". See attached screenshot.

![image](https://user-images.githubusercontent.com/791244/151248144-da36262c-1d21-482a-a4d9-62ad1b05d440.png)

**Comment by jcelerier** [comment]
oh, I think I see the issue: OSC addresses & names are case sensitive. In your screenshot you have `OSCDevice` instead of `OSCdevice` in the gradient.

I'd recommend drag'n'dropping the address to the green port directly, this way there's no way to make a typo. You can also right-click on the address box to bring up a menu which will allow to chose the OSC node.

**Comment by jcelerier** [comment]
I'll add an issue to add some way to detect such typos though, ideally having a panel that lists address which do not match any existing address in the OSC tree would be meaningful.
