### ISSUE TITLE
Videos look zommed in

### ISSUE THREAD

**Issue by AlvaroBeiro** [ossia/score#1470]
Create new project. Add a window. Size it to 1920x1080. Load a 1920x1080 video and link it to the window. It looks zommed in.

What ossia displays: 
![image](https://github.com/ossia/score/assets/11369738/e19f4dec-7bcb-4bd0-a04f-e02bd0c3a9d2)

What should be displayed:
![image](https://github.com/ossia/score/assets/11369738/52ee1b46-ff2d-4e17-8890-ce42083c45e7)

**Comment by jcelerier** [comment]
hello! you can set the stretch mode in the inspector, by default it displays the video at 1:1 scale. 
Can you send your test video file otherwise? as given what you says it should display it correctly but maybe there's some retina / hidpi thing to take into account

https://github.com/ossia/score/assets/2772730/961f0884-2026-4200-8ae6-cf920e5f2db7

**Comment by jcelerier** [comment]
(ps: sorry for the answer lag!)

**Comment by AlvaroBeiro** [comment]
Don't worry at all!

It happens with all videos. The one in my screenshot is just 

yt-dlp "https://www.youtube.com/watch?v=dPrqGpbSBpQ"

And my first test was with a render from Davinci Resolve at 1920*1080

Maybe it's the way that Ossia detects my screen as lower resolution, because it should just fit. Using Expand (Black Bars) displays the video in 1:1 for me so I can use it as a workaround.

Lenovo Legion Y520 Windows 10 laptop with 1920*1080 screen. It has an nvidia 1050 but the display output is through Intel HD Graphics.

**Comment by jcelerier** [comment]
ossia score 3.1.11 should have the bugfix :)
