### ISSUE TITLE
 libicuuc.so.52: cannot open shared object file (Ubuntu 16.04)

### ISSUE THREAD

**Issue by enrike** [ossia/score#186]
hi
I get this error with i-score from ppa

$ i-score
i-score: error while loading shared libraries: libicuuc.so.52: cannot open shared object file: No such file or directory

I see with "aptitude search" that libicu55, libicu-dev and icu-devtools are installed, but libicu52 is not available for install

i A libicu55  
i A libicu-dev
i A icu-devtools

maybe I should try to compile from source?

thanks, best

enrike

**Comment by jcelerier** [comment]
hi, indeed i-score has been built for ubuntu 14.04 and generally software built against one version of ubuntu don't work in another, unless you take the least common denominator path and build everything statically against a very old version.

A path that I'd like to engage more for Linux releases is instead to build AppImages / flatpack / xdg-app / snappy packages. For instance Krita is distributed like this : https://krita.org/download/krita-desktop/ ; this way you just have to download a file from the website and it will work in _any_ recent distribution.

But for now, yes, the easier would be to build from source. I'm quickly doing a build in a docker container and let you know all the required commands ASAP.

**Comment by jcelerier** [comment]
Here is a build procedure for 16.04 : 

```
apt install g++ libxml2-dev ninja libboost-dev qt5-default qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev libqt5websockets5-dev git cmake libportmidi0 libasound2
git clone https://github.com/Jamoma/JamomaCore --depth=1

mkdir jamoma-build
cd jamoma-build
cmake ../JamomaCore
cmake --build . --target package -- -j8
dpkg -i JamomaCore-0.6-dev-Linux.deb 

cd ..


git clone https://github.com/OSSIA/i-score
cd i-score
git submodule update --init --recursive
cd ..
mkdir i-score-build
cd i-score-build
cmake ../i-score -DISCORE_CONFIGURATION=static-release -DCMAKE_PREFIX_PATH=/usr/local/jamoma/share/cmake/Jamoma
cmake --build . -- -j8
```

**Comment by jcelerier** [comment]
Hi, 
I took some time in order to try to build an x86_64 AppImage (binaries that should work on any linux distro). Could you test it on yours ? 
Thanks.

@probonopd if you are interested in trying this would help me a lot; the next step would be to use Travis CI to run a CentOS container and do the build from this but I don't know how to handle it properly...

The appimage is here and has to be marked executable : 
https://github.com/OSSIA/i-score/releases/tag/v1.0.0-a68

**Comment by probonopd** [comment]
@jcelerier sure, happy to help. Assuming that you want to target CentOS 6 and later target systems: does https://github.com/OSSIA/i-score/blob/master/CMake/Deployment/Linux/AppImage/Recipe run without any errors on CentOS 6 for you? (It seems that the build deps do not get installed)

**Comment by enrike** [comment]
hi

Thanks, I was able to compile it under 16.04 following your instructions.

Now I just downloaded the x86_64 AppImage and it seems to work find on my desktop running Ubuntu 14.04.4 LTS. Tonight I will try to test it on my laptop with 16.04. I will let you know...

**Comment by jcelerier** [comment]
nice, thank you :)

**Comment by probonopd** [comment]
The challenge is always to make it work on older distributions - so which is the oldest distribution that you are targeting with the AppImage @jcelerier?

**Comment by probonopd** [comment]
@jcelerier your AppImage runs (read: launches successfully) on
- CentOS-6.7-x86_64-LiveCD.iso
- Chromixium-1.5-amd64.iso
- Fedora-Live-Workstation-x86_64-22-3.iso
- Fedora-Live-Workstation-x86_64-23-10.iso
- kali-linux-2016.1-amd64.iso
- kali-linux-2.0-amd64.iso
- kubuntu-15.04-desktop-amd64.iso
- kubuntu-16.04-desktop-amd64.iso
- ubuntu-14.04.1-desktop-amd64.iso
- ubuntu-16.04-desktop-amd64.iso
- ubuntu-gnome-16.04-desktop-amd64.iso
- ubuntu-mate-16.04-desktop-amd64.iso
- xenial-desktop-amd64.iso

It fails due to missing `libxcb-render-util.so.0` on
- CentOS-7.0-1406-x86_64-GnomeLive.iso
- CentOS-7-x86_64-LiveGNOME-1511.iso
- debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso
- elementary_OS_0.3_freya_amd64.iso
- kubuntu-14.04.4-desktop-amd64.iso
- SL-72-x86_64-2016-02-03-LiveDVDgnome.iso
- ubuntu-12.04.5-desktop-amd64.iso
- ubuntu-12.10-desktop-amd64.iso
- xubuntu-16.04-desktop-amd64.iso

This library is needed by `lib/qt5/plugins/platforms/libqxcb.so`.

**Comment by jcelerier** [comment]
hi, thanks so much for testing ! how did you test so quickly ? did you have some kind of some test suite that I could use or do you just run VMs by hand ? 

Also while I built the image on centos 6.8, when creating another VM instance of the centos live cd and trying to run the appimage it won't open :( it works for me in ubuntu 14.04 and 16.04 however.

**Comment by probonopd** [comment]
Yes, I am using https://github.com/probonopd/AppImages/blob/master/test.sh

The CentOS 6.8 thing is strange, what error messages did you get? Sometimes setting `LD_DEBUG=libs ./theAppImage` helps to identify issues.

**Comment by jcelerier** [comment]
ah, indeed it was due to libxcb-render-util here too. Strange that it is in 6.7 and not in 6.8 but well :) . (I also had to chmod +x /usr/bin/fusermount but I guess that it's a matter of the distro).

**Comment by probonopd** [comment]
You are bundling 8 MB of fonts, is this intentionally?

**Comment by jcelerier** [comment]
I had forgotten them, I fixed this in the latest recipe. Also added libxcb-render-util and his little friends (libxcb-icccm and libxcb-image were also missing but it seems that it would still launch).

**Comment by jcelerier** [comment]
@probonopd I managed to set-up a docker + travis ci workflow that will produce AppImages for the releases.
Thanks !

**Comment by probonopd** [comment]
@jcelerier that is awesome! Would you mind [writing up](https://github.com/probonopd/AppImageKit/wiki/Docker%20Hub%20Travis%20CI%20Workflow) what you did? I am sure that would greatly help others who would like to do the same.

I also linked you project on https://github.com/probonopd/AppImageKit/wiki/AppImages

**Comment by jcelerier** [comment]
@probonopd I wrote the most important things down. I hope that people will find it to be useful !

**Comment by probonopd** [comment]
Thank you very, very much @jcelerier. I am sure people will. In fact, I learned a thing or two myself :+1:

**Comment by yanxiangyi** [comment]
`wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3_amd64.deb`
`sudo dpkg -i libicu52_52.1-3_amd64.deb`
`sudo apt-get -f install`
