### ISSUE TITLE
rename i-score 0.3 into 1.0 everywhere

### ISSUE THREAD

**Issue by theod** [ossia/score#25]
I don't know where this version number appears in the repository so I assign it to you @jcelerier but I also  add @bltzr @jln-  and @nvuaille if they have any idea where to change this.

**Comment by jcelerier** [comment]
are we all sure that the final product is "i-score 1.0" ? (I'm for i-score 3 personally because I think that for some people, "i-score 0.2" equals "i-score 2"). 

I don't think that the version number actually appears somewhere in the software, only the current git commit is shown in the About section.

**Comment by jcelerier** [comment]
Anyway, this is now settable in the root CMakeLists.txt.
