### ISSUE TITLE
Windows release: cannot find msvcp140d.dll

### ISSUE THREAD

**Issue by RVirmoors** [ossia/score#274]
Hi!
The .exe won't run, claims it needs that *d.dll file. The "d" at the end is for Debug, I believe.. So you probably compiled in Debug mode instead of Release.

Then again on the wiki you say MSVC can't be used for building i-score (I haven't tried myself), so I'm confused :)

**Comment by jcelerier** [comment]
Damn, sorry, the wiki must not be up-to-date, MSVC is now the preferred way to build i-score (for a long time it couldn't build there due to the use of modern C++, but since VS2015 update 3 it is not the case anymore; and MinGW had its fair share of problems).

I don't have access to a windows machine currently but I'll try to see if something is not set-up correctly in the build scripts. thanks !

**Comment by jcelerier** [comment]
this should have been solved by 20b2bca ; the fix will be in the next release (in the meantime there are windows binaries here : https://ci.appveyor.com/project/JeanMichalCelerier/i-score/build/artifacts )

**Comment by jcelerier** [comment]
Closing, I tested on a clean Windows 10 install and so far it seems to work.
