### ISSUE TITLE
Don't lock states vertically

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#338]

**Comment by eirikblekesaune** [comment]
The problem also shows it self when I make a new state at the same event. I have to move the cursor a bit to the right, about to make both a new constraint(which _of course_ makes a new timenode) and a new state. Then I have to go back with the mouse to the previous timenode and release the mouse in order to make this new state in the same event.
The same thing happens if I hold the <alt> key and try to make a new event in the same timenode.
