### ISSUE TITLE
add a menu to specify different accessible parameters on automation

### ISSUE THREAD

**Issue by pach** [ossia/score#379]
<img width="356" alt="capture d ecran 2017-02-23 a 11 43 00" src="https://cloud.githubusercontent.com/assets/365923/23255855/617b83fa-f9bd-11e6-8292-eff3a61b8da5.png">

if selectionning for example polar for a position, there is no clue to know the different accessible attribut. Add a third menu would be great to select which attribute you do want to automate.

**Comment by jcelerier** [comment]
what if instead of a menu, it showed in parentheses what's available ? 

e.g. `polar [r, theta]`, `cart2D [x, y]`, etc.

**Comment by bltzr** [comment]
my position is that, with a menu, we could choose from there, and avoid the user to have to type it in the address field.
I'm not advocating that we remove the @[dataspace.unit.element] syntax, but that we make it possible for users to fill it through menus
so, in the above example, if we chose e.g. 'a' in the third menu, it would fill the address field with .../position@[position.polar.a], so we can keep both accesses and keep both GUI and command line users happy
does that make sense ?

**Comment by bltzr** [comment]
related to #369 

(jm: copy pasting your comment here for clarity: 

it would be nice to have a menu for accessing tuple elements in the address fields (e.g. for automations, condition/trigger expressions, etc...

when no dataspace/unit is set, we would have, for a n-uplet:

    *
    1
    ..
    n

when a dataspace is set (e.g. xyz position):
then we have a first menu, which offers the different "units":

    xyz
    aed
    etc....
    and then another menu that proposes the possible options (e.g. for xyz) for this one automation/expression:
    *
    x
    y
    z

)

**Comment by jcelerier** [comment]
## To do 

Everything is handled in `UnitWidget`. Instead of working with `Unit` it should work with `DestinationQualifiers` instead (unit is just `rgb`, unit + destination qualifier is `rgb.r`).

Some code has to be added (likely a `on_unitChanged`) to update the combobox with the list of relevant qualifiers for this unit. The combobox should be disabled if it does not makes sense (e.g. for speed or time or distance). The only array-like units are position, orientation, color.

Every unit's textual accessors are in the unit's `array_parameters()` functions (which returns a string, e.g. "rgb" for a rgb color or "xy" for a 2D point). The simplest way is to use `ossia::get_unit_accessors(theUnit)`.

Finally, if there is no unit, display an editable QComboBox with the array index as mentioned in the previous comment.

**Comment by jcelerier** [comment]
![units](https://user-images.githubusercontent.com/2772730/44093177-0881391c-9fd3-11e8-9b65-670b3c7cfa49.gif)
