### ISSUE TITLE
Execution speed weirdness

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#424]
@pchdev could you explain how to reproduce ?

**Comment by jcelerier** [comment]
maybe it's the same problem than https://github.com/OSSIA/libossia/issues/56 ?

**Comment by pchdev** [comment]
probably the same thing, yes, didn't see that one on libossia

see enclosed scenario: it gets an extra delay at each event. I guess I managed to avoid it in the past because I wasn't really using loops or precise/synchronous events, but it gets indeed really problematic in that case

[delay.scorejson.zip](https://github.com/OSSIA/i-score/files/907402/delay.scorejson.zip)

**Comment by jcelerier** [comment]
yep. I'd like to have your input on the libossia bug if possible ! (for instance what kind of behaviour you'd prefer by default, etc)
