### ISSUE TITLE
shouldn't there be separate bound modes at each bound ?

### ISSUE THREAD

**Issue by bltzr** [ossia/score#431]
Not sure about that, but that would be more simple/elegant ?

**Comment by bltzr** [comment]
I mean, we could have clip at min and fold at max

**Comment by bltzr** [comment]
I'm speaking of properties of a node/value in the device tree of course

**Comment by jcelerier** [comment]
that's honestly somewhat tedious to do (and may impact the performance a bit since now we have to check for different bounds at min and max). Basically this would have to be.. maybe not rewritten, but changed quite a bit to allow for both bounds : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia/network/domain/detail/domain_impl.cpp

**Comment by bltzr** [comment]
ok, no problem

should I close the issue, then ?

**Comment by bltzr** [comment]
closing the issue, as this is less than secondary
