### ISSUE TITLE
position+zoom scrollbar -> scenario map

### ISSUE THREAD

**Issue by pach** [ossia/score#437]
Certes, le shift-molette existe mais pas forcément intuitif à trouver. Et sans déplacement horizontale, i-score devient vite une réel purge à utiliser à la souris.

--- Sure, the shift-scroll exists but is not necessarily intuitive to find. And without horizontal scrolling, i-score quickly becomes a true bane to use with mouse

**Comment by jcelerier** [comment]
@jln- @blueyeti @bltzr where does this go in the UI ?

**Comment by bltzr** [comment]
ben idéalement, ça serait la map dont on avait parlé, mais c'est ptêt pas pour demain matin ;-)

en attendant, est-ce qu’on ne peut faire un ascenseur (à la place du zoom) qui permette de manipuler simplement position (avec la position en X) et zoom (avec taille du slider, qu’on puisse changer, par ex. par un mouvement vertical ?) ?? 


--- well ideally, it would be the map we have been talking of, but it may not be for tomorrow morning ;-)

in the meantime, couldn't we make an elevator (instead of the zoom) which would allow to handle easily position (with the position in X) and zoom (with slider size, that we could change, for instance, by a vertical movement ?) ??

**Comment by pach** [comment]
Le slider zoom + position me semble pas mal.
On le retrouve dans pas mal de logiciel en soit...

----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

2017-05-05 8:38 GMT+02:00 Pascal Baltazar <notifications@github.com>:

**Comment by jcelerier** [comment]
est-ce que vous avez un petit screenshot d'un truc existant ?

**Comment by pach** [comment]
![sliderzoommove](https://cloud.githubusercontent.com/assets/365923/25738224/23b4447a-317c-11e7-978c-96b454d6cacb.gif)
ça c'est dans after. Plutôt efficace et précis.

**Comment by jcelerier** [comment]
ah, oui. la barre de temps en haut fait le slide mais pas le zoom. ça pourrait se rajouter là ? (à vrai dire je crois qu'elle l'a fait fut un temps mais ça marchait pas très bien donc désactivé)

**Comment by pach** [comment]
La seconde barre de temps en dessous des infos de temps? c'est la zone de rendu active.
Ici c'est plus l'idée d'avoir un slider de temps extensif, ou les poignées gauche et droite permettent de zoomer dans le temps et sa taille indique le niveau de zoom. Et son déplacement gauche droite permet de se déplacer dans le temps donc.

**Comment by bltzr** [comment]
oui, c'est ce genre de sliders auquel je pensais, celui-ci est vraiment bien foutu
par contre,  @jcelerier, tu parles de la barre d'i-score, hein ? 
perso, je trouve ça inhabituel de mettre cette barre de position/zoom en haut, au-dessus de la barre de temps, mais c'est vrai qu'à la réflexion c'est plus logique

**Comment by bltzr** [comment]
et ça permet de garder un même positionnement pour le jour où cette barre position+zoom deviendra une map, donc pê que ça vaut le coup de la placer en haut dès à présent
de plus, je ne vois pas l'intérêt que la barre de temps soit aussi haute qu'actuellement. On pourrait facilement la réduire de moitié

**Comment by pach** [comment]
Ah oui tiens, on peux deplacer avec la barre de temps...
Du coup c'est le slider du bas qui trompe et ne nous fais pas penser à
cette option... ^^

----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

2017-05-15 13:15 GMT+02:00 Pascal Baltazar <notifications@github.com>:

**Comment by bltzr** [comment]
@lossius commented on #173 : 
Would it be possible to extend the scrollbars in i-score with small handles at the end that could be used to click and drag zoom-in and zoom-out? Reaper behaves this way.

Additionally, when holding the cursor over the horisontal (time) scrollbar and pinching/zooming at the trackpad, or using the scroll wheel, it would be nice if this also would be zooming in and out in time rather than scrolling up and down.

There's a screencast here that illustrates how this works in Reaper:

https://sourceforge.net/p/i-score/mailman/attachment/0945D7F2-6A2D-41AE-978C-4E3A457E2152%40bek.no/1/

**Comment by bltzr** [comment]
in the future, this could become a scenario map, as in several DAWS, and as it has been discussed recently...

**Comment by jcelerier** [comment]
closing due to minimap implementation, please reopen if issues arise
