### ISSUE TITLE
input and output are inverted when creating a device

### ISSUE THREAD

**Issue by reno-** [ossia/score#44]
In the panel for creating a new device, input and output are inverted

**Comment by reno-** [comment]
both Minuit and OSC devices have inputed inverted.

**Comment by jcelerier** [comment]
@theod: from the doc of the API (Minuit.h) : 

```
/*! factory
\param std::string ip of the Minuit device
\param int port where to send messages
\param int port where messages are sent back
\return std::shared_ptr<Minuit> */
static std::shared_ptr<Minuit> create(std::string, int, int);
```

But the implementation says : 

```
shared_ptr<Minuit> Minuit::create(std::string ip, int in_port, int out_port)
{
  return make_shared<JamomaMinuit>(ip, in_port, out_port);
}
```

What should I believe ? It looks like here, "input port" means "input port of the remote device" and I think that @reno- expects it to be the other way round.

**Comment by reno-** [comment]
Ah ok, I understand the misunderstanding…
The panel is reffering to the device, but because I'm editing it in i-score, I thought it was related to i-score flow from/to this device.
So if @bltzr , @avilleret , @cbossut  and other users are fine with this panel, I will agree to.

![capture d ecran 2015-11-10 a 11 16 22](https://cloud.githubusercontent.com/assets/127730/11059855/7e5d6fea-879c-11e5-9880-b18d26343759.png)

**Comment by reno-** [comment]
sorry for the noise

**Comment by jcelerier** [comment]
I must admit that this is a bit counter-intuitive to me too. Maybe I should replace the text with "Remote input" and "Remote output" ?

**Comment by bltzr** [comment]
I also think that because I'm editing it in i-score, it should be related to i-score
I.e. My vote would go for inverting the names - not sure that adding "remote" helps much...

**Comment by theod** [comment]
in the API the point of view is on the remote device side but this will change when I'll rewrite the API network.

**Comment by avilleret** [comment]
two port numbers is confusing, so my suggestion : keep only one ! :-)
why should we define the i-score listening port per device ?
couldn't it be a global setting and all devices connect to the same port ?
Thus the only relevant port information in the device setting is the device listening port.
But I know this would make a big change in the whole networking concept.
If it's too much change, I suggest at least to use "i-score listening port" or "device listening port" rather than input/output port (because the input port of i-score is the output port of the device and _that_ is confusing).
Moreover adding a small info-bulle with "from i-score to device port" or "from device to i-score port" would definitively clarify any doubt. (at least for me)

**Comment by theod** [comment]
your proposition is part of the rewrite I have to do for API Network.

for example in the future i-score will be a MinuitServer(13579) and a MinuitClient(9998, "localhost") and you Pd patch will be a MinuitClient(13579, "localhost") and a MinuitServer(9998).
this way it will be possible to define a one way communication if we don't need to control/explore i-score for example (with Pd as a MinuitServer and i-score as a MinuitClient only).

but I'll start this rewrite in december after the IRCAM workshop.

**Comment by theod** [comment]
however what I said above is not solving the design of the i-score network panel interface and I agree that we need to make this clearer as possible using long sentences to explain what parameters mean.

**Comment by avilleret** [comment]
hum... my proposition is to have a bi-directionnal communication for each device but to use the same listening port on i-score for all device. 
for example, I have a video generation patch on Pd that connects to i-score on port 13579 and listen to port 9998, and another Pd patch making sound effect that connects to i-score on port 13579 (the same as above) but listen to port 9999 (since 9998 is already busy).
afaik device always announce itself with minuit protocol, so this shouldn't be a problem to have multiple device sending data on the same UDP port, isn't it ?

**Comment by theod** [comment]
no problem because the Minuit syntax provides device name at the beginning or each request or answer.

this is one of the basic idea of Minuit but I'm not sure it is such a good idea for performance as it means we need to do a string parsing to know who is speaking. actually a better specification would to have one in and out port dedicated to each device IHMO. 

but in the same time I think we should keep Minuit as it is (a protocol designed to raise and solve workflow problems considering applications are able to describe themselves) and work on OSCQuery specifications instead.

**Comment by bltzr** [comment]
> Antoine I think your naming proposals are good 

Re: i-score's listening port in Minuit I agree there's no reason to change it at all....
Though with OSC devices we need to define both ports

**Comment by reno-** [comment]
Yes, I think too that each OSC device must have a dedicated port to send data to i-score.

**Comment by reno-** [comment]
So, I try to abstract : 
• for Minuit device : 'i-score listening port' could be defined in the main preferences panel when it will exists, and for now it could be 13579. So when you create a minuit device, you just have to define the 'device listening port'.
• for OSC device we should have to define both 'device listening port' and 'i-score listening port'.
