### ISSUE TITLE
create headers for processes in fullview

### ISSUE THREAD

**Issue by bltzr** [ossia/score#656]
there should be 
- [x] the little handle to reorder processes,
- [x] the name of the process

some day:
- [x] the min and max values
- [x] the unit

**Comment by jcelerier** [comment]
one has to refactor what's in TemporalConstraintPresenter.cpp, eg put the DefaultHeaderDelegate in its own file, and also use it in FullViewConstraintPresenter

**Comment by jcelerier** [comment]
(Also drag'n'drop of slots still has to be implemented... cf QDrag and dragEnterEvent & friends in QGraphicsItem)

**Comment by avilleret** [comment]
for drag'n'drop see #655

**Comment by avilleret** [comment]
@bltzr I don't see where you define the name of the process, is this something that should be implemented too ?

**Comment by bltzr** [comment]
I think it's generated by the process itself (e.g. target address for automation)

There used to be a field to change the name in the old days:
- changeable until at least a70
- static after that

I think this disappeared when we made the separation between the different objects in the inspector

**Comment by bltzr** [comment]
The question about If we need to resurrect this name field is an open question
I'd say: "why not ?"

**Comment by avilleret** [comment]
like that : 

![image](https://user-images.githubusercontent.com/504914/33393003-fea5e470-d53d-11e7-8c7e-ee7ab45db1f4.png)

**Comment by avilleret** [comment]
Concerning the name of the process, finally I don't like it very much because most of processes have different view.
It's only relevant for interpolation/automation discernement (and this issue only concern them btw), and since Interpolation doesn't have "unit", nor min and max, I thing a different color should be enough to distinguish them.
What do you think @bltzr ?

btw some feature are already implemented in https://github.com/OSSIA/score/tree/feature/656-slotHeader

**Comment by bltzr** [comment]
I still think it's good to have the process name: there is space for that and it helps getting an idea of what we're dealing with
my 2 brouzoufs
