### ISSUE TITLE
display speed on hover directly on the interval's header

### ISSUE THREAD

**Issue by bltzr** [ossia/score#658]
at execution only

ideally with a slider and number box displaying the current speed

**Comment by jcelerier** [comment]
To do : 

* Choose what happens when the interval is very small
* Implement a slider with QGraphicsItem (using a QSlider would be very ugly)
* Put this in IntervalMenuOverlay maybe ? it should be possible to check if the interval is currently executing with a new "executing()" member in IntervalView (there is already `setExecuting` in there so that should be easy)
