### ISSUE TITLE
array interpolation

### ISSUE THREAD

**Issue by pchdev** [ossia/score#66]
_Feature request_

I think it would be nice to reintroduce (as it was before with the 0.2 v) interpolation between two states of a same array. For example, I have an array of 16 values for my jamoma granular synth module, each one being a pitch value for each grain, and I wanted to interpolate them simultaneously, in "one block", rather than taking them individually. 

Pierre

**Comment by bltzr** [comment]
oooh, yes ! 
@lossius also requested that while in Bordeaux.
This is something we've added to the asana todo-list, but it didn't make it to i-score... yet...
One of the main question asked by @jcelerier was whether we created a curve for each member of the array ? I think we should...
Though, maybe there's a better solution in the meantime, but I'm not sure which...
Maybe allowing to interpolate, but displaying no curve ?
opinions ? @jln- @theod @reno- ?

**Comment by theod** [comment]
the API is designed to allow curve tuple.

in the future the interface should depend of the "dataspace" of the parameter.
if it is a position parameter I would like to be able to work with trajectories, if it is a color parameter I would to work with gradient in time (like in Duration software), ... but of course this is a feature for next version and so I would choose to display one curve per element of the tuple for now.

**Comment by jcelerier** [comment]
what should happen in the case where three curves are created and then one or two of these curves are removed ?

**Comment by lossius** [comment]
Personally I'd say that it is more important to be able to use arrays with dataspace than to enable individual curves for each array member. Dataspace is important e.g. in order to swap between straight-line and circular spatial movements, and is a more meaningful way of describing the desired results than having to specify curves individually for each array member.

Also I believe that this should be designed according to "convention over configuration". 99% of the time we probably want to apply the same curve to all members of the array, and the possibility of describing them individually should not clutter this by enforcing us always to set up three curves (for position xyz)  rather than one.

As for your question @jcelerier : The first curve should be default be applied to all array members unless another curve is described and overrides the default.

**Comment by jcelerier** [comment]
Should work in latest version.
