### ISSUE TITLE
UI does not display message values

### ISSUE THREAD

**Issue by pchdev** [ossia/score#74]
Hi !
message implementation works great, thx @jcelerier ! yet, there's still a small issue with the UI: when typing a message in the "value" field (next to the "address" field) of a start/end state, the string is "recorded", and sent to the device when reaching the chosen state, but the value is not displayed in the field

Pierre

**Comment by jcelerier** [comment]
I think that this was due to invalid conversion between char and string.

note to everybody : 
in i-score, file https://github.com/OSSIA/i-score/blob/master/base/plugins/iscore-lib-state/State/ValueConversion.cpp there are many conversion functions that are used to convert from Qt's textual formats to iscore's value type.

For instance : https://github.com/OSSIA/i-score/blob/master/base/plugins/iscore-lib-state/State/ValueConversion.cpp#l263..l280

this part converts a value into a QChar. So for now I transform it in '-' if I don't know what to do with it (e.g. we have an impulse in input, what do we want to display if the address type is Char ?).
Please check there the conversions that are required.

**Comment by theod** [comment]
it seems ok.
is it still a problem for you @pchdev ?

**Comment by pchdev** [comment]
sorry.. didn't check my github messages lately.
and no, it's still not working for me it seems unfortunately

**Comment by jcelerier** [comment]
Maybe it's because the value was very dark on black ? I changed the value to light-gray (returns) and dark-gray (messages).

**Comment by pchdev** [comment]
yep, now I see :) 
thanks!
