### ISSUE TITLE
Serial protocol limitations

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#756]
_Altho the message window reports received messages, the "onMessage" function dosn't seem to return anything.

_neither "min", "max" or "Acces" show up in the Device Explorer after being set in the Qml code for the Serial protocole   

explained in greater length in http://forum.ossia.io/t/arduino-communiction/47

**Comment by jcelerier** [comment]
now works

**Comment by thibaudk** [comment]
-  [x] "Bool", "Char" and "VecNf" aren't implemented yet for Serial 
- [ ] Parent nodes sow up as "Impluse" types
- [ ] "min", "max", "Acces", "Description" & "Units" don't show up in the Device Explore
- [x] There is no way to avoid sending the '\n' at the end of each messages. 
- [x] Inversly, there is no way to receive messages if they don't end with '\n'

**Comment by jcelerier** [comment]
> _"Bool", "Char" and "VecNf" aren't implemented yet for Serial

I did them yesterday, though list and impulse are missing

For the \n, it's an inherent problem of the serial "protocol", which is a continuous stream of data (e.g. there is no notion of independent "messages") : either a delimiter has to be chosen, or one of the various techniques used here have to be applied:  

https://electronics.stackexchange.com/questions/186254/serial-protocol-delimiting-synchronization-techniques

\n is the simplest to use because it cleanly maps to line if you want to debug your serial device elsewhere. If it's needed  we could also use some of Qt's common serial protocol implementations (CAN and Modbus) : https://doc.qt.io/qt-5/qtserialbus-index.html ; implementing Firmata would not be too hard because it's basically MIDI.

**Comment by thibaudk** [comment]
Thanks for all the details!
'\n' is indeed very useful for receiving data and it is very handy to have it as default. 
A few Arduino examples also provide Processing an Max5 patches as counterparts and use "byte stuffing" or buffering to constitutes messages as chunks of N bites (if I a not mistaking).
Here are some of these examples (the processing code is provided inside the sketch in comments):
[https://www.arduino.cc/en/Tutorial/Dimmer](url)
[https://www.arduino.cc/en/Tutorial/SerialCallResponse](url)

Keeping the '\n' as default, an additional argument to overide it in the onMessage function for receiving and to the 'request' for sending could offer greater flexibility.
CAN and Modbus might just be it.
This is not however a fundamental issue.

More pressing are the implementation of types (well done for the existing ones!)
that will hopefully fix #891

**Comment by jcelerier** [comment]
can you tell me if with the libossia branch feature/raw_serial it works as you expect ? there shouldn't be any '\n' anywhere now. If it does I will merge it to master so that it is in the next release.

**Comment by csaudiodesign** [comment]
> can you tell me if with the libossia branch feature/raw_serial it works as you expect ? there shouldn't be any '\n' anywhere now. If it does I will merge it to master so that it is in the next release.

I'm trying to get the output of IMU sensors (gyro/accel/magn) into score. I wrote a custom serial protocol that allows for frame synchronisation and fixed frame size - aiming for predictable frame rate. Reading the changes in the libossia feature/raw_serial branch I understand that you're converting the QByteArray to a string. Wouldn't it be more interesting to convert to a JavaScript ArrayBuffer, which allows the user custom conversion in QML?

Example of my use case:
- Frame of 9 bytes: `255 255 ax_msb ax_lsb ay_msb ay_lsb az_msb az_lsb 0`
- Concatenate ArrayBuffers and split at the sequencing marker `0 255 255`
- `ax_msb` and `ax_lsb` are added up to uint16_t: `(ax_msb << 8) + ax_lsb` etc.
- the resulting sensor values are assigned to ossia device addresses

I see where this might be problematic: onMessage is probably supposed to be stateless and therefore concatenation of values between onMessage calls impossible. Do you see another way of implementing custom serial communication protocols without having to alter the libossia codebase for each protocol?

**Comment by jcelerier** [comment]
Hi @csaudiodesign ! last time I checked, Qt's JS engine did not really support the JS Array things (typed array, etc). It supports them from within the QML/JS language itself but I could not find a way for instance to create an Uint8Array from C++ to pass it to the JS engine. If you know a way to do it that would definitely be the better thing to do as we would not loose any information this way.

**Comment by csaudiodesign** [comment]
Hi @jcelerier ! Thanks for the super fast response. I'm not familiar with QT, just digging in now to find a solution for this. It will take a while. I thought it should be easy because of the [automatic conversion of QByteArray to JS ArrayBuffer](https://doc.qt.io/qt-5/qtqml-cppintegration-data.html#qbytearray-to-javascript-arraybuffer), but I guess I misunderstood something. I assumed it should be possible to use `new Uint8Array(arr)` in JS, `arr` being the ArrayBuffer converted by the QT JS engine. I will try to figure it out.

**Comment by jcelerier** [comment]
hmm, last time I had looked into it it did not work - maybe now it does (or maybe I just made some dumb mistake last time !) ... trying !

**Comment by jcelerier** [comment]
hhmmmm I don't see how it can work without a non-trivial refactoring :( we use QJSValue::call to call back the JS function defined by the user: https://doc.qt.io/qt-5/qjsvalue.html 

Arguments to call is a list of QJSValue. The problem is that there is no way to construct a QJSValue from a QByteArray, only from QString / QLatin1String: 

```C++

    QJSValue(bool value);
    QJSValue(int value);
    QJSValue(uint value);
    QJSValue(double value);
    QJSValue(const QString &value);
    QJSValue(const QLatin1String &value);
```

**Comment by jcelerier** [comment]
oh wait ! it seems that with QJSEngine::toScriptValue it indeed works.

**Comment by jcelerier** [comment]
we should check how much it breaks, @thibaudk what do you think ?

**Comment by thibaudk** [comment]
Hey ! I think Serial port was due for a big reflector anyways, as are the current devices in the library.

**Comment by jcelerier** [comment]
okay, so let's just do the change in that branch.

**Comment by jcelerier** [comment]
done and merged :) i'll write a doc page which explains how to access the raw byte stream from JS

**Comment by jcelerier** [comment]
I think we're good :) 

@csaudiodesign, here is how things will look: https://ossia.io/score-docs/devices/serial-device.html
