### ISSUE TITLE
Stream audio sample from disc option

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#772]
Ram use can be quickly saturated when loading "sound file" processes with fairly big audio tracks.
Adding an option to stream direct from disc would add a lot of flexibility.

**Comment by jcelerier** [comment]
just pushed a partial fix : currently sound files were loaded twice (once in the editor and once in the execution), now they will be loaded only once

**Comment by jcelerier** [comment]
A good start for this would be to : 
- do a memory map of the files (maybe with `#include <boost/iostreams/device/mapped_file.hpp>` since mmap is not there on windows ?)

- use this : https://stackoverflow.com/questions/9604633/reading-a-file-located-in-memory-with-libavformat to read them here : https://github.com/OSSIA/score/blob/master/base/plugins/score-plugin-media/Media/AudioDecoder.cpp#L728

Then once this part works, porting the whole thing so that it runs in the execution process instead of the UI : this certainly means reimplementing the current one : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia/dataflow/nodes/sound.hpp#L26 (the current one should stay, though, since it will be much faster if we have small files) 

We also need to read the whole thing at least once to generate the waveform (and maybe have a waveform cache somewhere).

**Comment by thibaudk** [comment]
Great! thank you for the pointers. 
I'll get on it and report my findings here.

**Comment by jcelerier** [comment]
done
