### ISSUE TITLE
Strange playback issue with Airpods and Spotify

### ISSUE THREAD

**Issue by eccoscreen** [ossia/score#778]
Hey I have a problem I'm facing while I'm listening to Spotify and working on a sketch in score. The playback in Spotify and Airpods goes to mono and low quality (which usually happens when the mic is on), and Score's play button has no effect. I can't press play in Score while listening to music.

Is there any way to disable the audio input on score so this stops happening? I can only switch to different drivers, but not disable any inputs.

macOS 10.13.4
score 2.0.0-a3

**Comment by jcelerier** [comment]
hi! I must say... this is certainly going to be a fairly interesting thing to debug.

are you using soundflower or something like this by any chance ? The problem sounds like both score and spotify fighting for control of the soundcard, but this generally does not happen at all on macOS, only on windows and some linuxes. 

If you are not using sound at all I can make a build which does not use the soundcard - it's only enabled in debug mode but not in the release because it led to some surprises with people disabling sound by inadvertance like this.

**Comment by eccoscreen** [comment]
@jcelerier 

Hi, I'm not using soundflower, but I do have a similar app called Audio LoopBack installed on my system. Though it's not active in my macOS sound preferences or in score's audio device settings. 

I'm not using sound in my sketch so if you do have a build without audio that would be fantastic.

**Comment by jcelerier** [comment]
a friend just told me that he had the same problem with spotify and other software - playback going to mono 11khz when plugging in external mics.

He told me that setting the system input to the mac audio input (not the airbuds's internal mike) in the system settings did fix it - maybe you can try this ?

**Comment by jcelerier** [comment]
I am pretty sure that this is this exact bug : https://www.jeffgeerling.com/blog/2018/airpods-get-stuck-low-quality-16-khz-audio-mode-when-starting-vm

which is squarely on Apple's side - I can't really do anything about it ; you could try to change the audio settings to only use the output but I'm not sure that it would work.
