### ISSUE TITLE
can't launch AppImage V2 due to QT5 version

### ISSUE THREAD

**Issue by dewiweb** [ossia/score#836]
I'm on linuxmint 19 and when I try to launch AppImage V2

>./Score-v2.0.0-a18-linux-amd64.AppImage
>bin/ossia-score: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by >bin/ossia-score)

**Comment by jcelerier** [comment]
can you try this one ? https://ufile.io/cr3kw

thanks !

**Comment by dewiweb** [comment]
It seems to be OK!
What's the differences betwwen official version and this one?

**Comment by jcelerier** [comment]
well, the official one had a bug :p 
basically, appimages contain a mini-filesystem with the necessary libraries (you can look inside it by running `./score.AppImage --appimage-extract`, it will be in the folder squashfs-root). 

I forgot to add (or rather, I removed at some point for some reason) the LD_LIBRARY_PATH=lib in the script which is launched at the start of the AppImage (the AppRun at the root of the extracted image), which tells linux to look for the libraries in the folder I give instead of the system one (which may have older or incompatible versions like you witnessed).
