### ISSUE TITLE
ossia v2.0.0-a25 doesn't startup on OSX 10.13.6

### ISSUE THREAD

**Issue by maybites** [ossia/score#879]
there is no error, only the startup screen appears but then nothing happens. the only way to close it is to kill it via 'force quit'. however, the system doesn't indicate that the app is unresponsive..

**Comment by jcelerier** [comment]
thanks for the report, there's a known bug where it does not start but only the first time, could you try to relaunch it to see if it's the same ? thanks !

**Comment by maybites** [comment]
still no success.

**Comment by jcelerier** [comment]
hmmm... by any chance, do you have jack running ?

**Comment by maybites** [comment]
no.

**Comment by jcelerier** [comment]
I suppose that there is something else going on, because other users have reported that it worked on 10.13. I'll post here if I think of something but for now, I've honestly no idea of what is going wrong

**Comment by maybites** [comment]
is there any log to the console? this might help to see up to which point the app gets before it stops. maybe it is waiting for something?

**Comment by jcelerier** [comment]
to have some log you should run it in a terminal : 

    $ cd ../score.app/Contents/MacOS
    $ ./score

but if it is just stuck, I'm not sure there will be a lot of interesting things.
If by any chance you have xcode installed, the best thing to do would be to try to launch it under a debugger and see where it stops : 


     $ lldb score.app
    ... wall of text ...
    Current executable set to '/Users/maybites/Downloads/score.app' (or something like this)
    (lldb) r

after typing "r" press enter and it will start.
    

and after some time, when it is stuck (wait something like 30 seconds just in case so that we can be sure that we are in the part of the code where it is stuck and not just loading - when running under a debugger everything is much slower) do the following : 

1. Press the ctrl-C key combination
2. type "bt" 
3. paste the output here 

it would be really nice, thanks ! (but I understand if you don't have time for this)

**Comment by maybites** [comment]
I found the reason for my hang:

there is a little dialog box "The desired audio settings could not be applied" that was hidden behind the splash screen. it only showed when I started the app from the console. 

once I clicked 'ok' the app started.

**Comment by jcelerier** [comment]
ah! this has been solved in the current git master, it will be in the next release. sorry for your trouble !
