### ISSUE TITLE
Temporal Rift when constraint on last event

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#90]
On dev (b19fc4b5550a7a8cf812483dadf141041f52faff) and probably on release v1.0.0-a31.

If a constraint end on the scenario EndEvent, moving backward the start event of this constraint will break it : an empty space appears and at execution, Time jumps over it.

Note : in this version, the real CSP is not used, only a fake one.

**Comment by theod** [comment]
I guess you are the one who can fix this @nvuaille ?

**Comment by nvuaille** [comment]
A subjacent question is : why an end event ?

**Comment by theod** [comment]
do you mean "why an end event" for the Scenario ?

**Comment by nvuaille** [comment]
Yep !  All right

**Comment by theod** [comment]
First of all a TimeProcess is always embedded by a TimeConstraint (which is also a Clock) and have 2 TimeEvents for the its start and its end. So it is not the Scenario who have a end event but its TimeConstraint.

Then the end event of the Scenario TimeConstraint can be triggered in different cases : 

- when the Scenario ended itself,
- if the Scenario TimeConstraint's Clock is not infinite because in the future it should be possible that someone wants to create a project with a static duration,
- if we allow to add a Trigger on it,
- when the end event will be exposed into the local device, some clients will be able to stop the Scenario TimeConstraint remotely by triggering the end event.

**Comment by theod** [comment]
oups ! sorry forget about the last comment (I just removed it)

**Comment by theod** [comment]
I've forgot there was an internal TimeNode for the end inside the Scenario class.
and I would say : let's try to comment it and see if someone need it ...

are you ok with this radical change in Scenario API @jcelerier (no more Scenario::getEndTimeNode()) ?

**Comment by theod** [comment]
just to be sure we are talking about the same thing :
this doesn't mean we'll remove the End TimeEvent of the TimeConstraint that handles the Scenario.

**Comment by jcelerier** [comment]
yes please, this would also simplify a lot what happens when you want to make the duration of a scenario smaller.

**Comment by nvuaille** [comment]
There is no rift with the CSP. But this last event can move and be executed before the end of the scenario : it's considered as a floatting event, like dropped ones.
