### ISSUE TITLE
javascriot seems to be bugged in last release

### ISSUE THREAD

**Issue by pach** [ossia/score#976]
The javascript default example (and any script I made) are sending a Nan as output.

https://gist.github.com/pach/5862bdee54fa73c1f6058ef28ec5846a

**Comment by pach** [comment]
After a second check, seems that the inputs are not parsed into javascript. 
if output value generation is only made from inside the script, works just fine.

**Comment by thibaudk** [comment]
As a workaround, you can use "ControlInlet" instead of "Valueinlet".
"ControlInlet" seem to still work fine

**Comment by pach** [comment]
so the question will be : what's the difference between a ControlInlet and ValueInlet?

**Comment by jcelerier** [comment]
hiya ! 
basically, ValueInlet is for messages (e.g. it will only have a value at the exact tick where you receive a message) while ControlInlet is more like a knob (it will always have a defined value)

**Comment by jcelerier** [comment]
e.g. if I add a state I get an output at the correct point : 
![in](https://user-images.githubusercontent.com/2772730/67150996-73fac380-f2bf-11e9-9a54-4e85dfd1c4ad.png)

**Comment by jcelerier** [comment]
what I can do however is not sending a message if it's a NaN so that it does not break things but if you use ValueInlet the value should be checked like this : 

![ok](https://user-images.githubusercontent.com/2772730/67151003-a0164480-f2bf-11e9-8e2e-86238d77325d.png)

I will adjust the default so that it uses ControlInlet which is what most people what by default I think (but ValueInlet is still useful for stuff like drum triggers for instance)

**Comment by pach** [comment]
yes, And might probably be good to update the default example when create a javascript node. ;)
Thanks.
Thomas

**Comment by jcelerier** [comment]
I updated the documentation with the current state of things here - now it should not need to change anymore

http://ossia.io/score/features/javascript.html
