### ISSUE TITLE
a .gitignore file is installed in /usr/include

### ISSUE THREAD

**Issue by ycollet** [ossia/score#979]
A .gitignore file is installed in /usr/include during make install

**Comment by jcelerier** [comment]
should be good now, at least I'm not seeing a .gitignore being installed here.

Note that for installing it should be 

```
cmake -DCMAKE_INSTALL_DO_STRIP=1 -DCOMPONENT=OssiaScore -P cmake_install.cmake
```

instead of just `make install` as `make install` installs additional things that are needed when making the self-contained releases (see the wiki here: https://github.com/OSSIA/score/wiki/Packaging-score-for-Linux).

thanks !
